version: '3'

services:
  dind:
    build:
      context: https://github.com/alfredriesen/docker-container.git
      dockerfile: DockerfileDinD
    container_name: "dind"
    ports:
      - "51212:22"
    environment:
      TZ: ${TZ}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - .:/app
