version: '3'

services:
  dind:
    build:
      context: ${STACK_PATH}/${STACK_ID}
      dockerfile: DockerfileDinD
    container_name: "dind"
    ports:
      - "51212:22"
    environment:
      TZ: ${TZ}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ${STACK_PATH}/${STACK_ID}:/app
