version: '3'

volumes:
  app:
    name: dind-${APP_NAME}-volume

services:
  dind:
    build:
      context: https://github.com/alfredriesen/docker-container.git#dind
      dockerfile: Dockerfile
    container_name: dind-${APP_NAME}
    ports:
      - ${SSH_PORT}:22
    environment:
      TZ: ${TZ}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app:/root
